"""reports catalog: one row per object, not per incident

The initial schema made incident_id unique among live rows, assuming one
report per incident. The real corpus disproves it: 8 incident ids appear in
two files each (an original and a later revision), so that constraint would
have rejected the second file of every pair and silently lost 8 reports at
migration time.

Uniqueness moves to object_key, which is genuinely one-to-one with a stored
blob. incident_id keeps a plain index — it is still the column you query by,
it just is not a key.

Revision ID: 06a1177882ba
Revises: 225d067584d5
Create Date: 2026-08-04 22:52:33.237917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a1177882ba'
down_revision: Union[str, Sequence[str], None] = '225d067584d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_reports_incident_live'), table_name='reports', postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_reports_incident', 'reports', ['incident_id'], unique=False)
    op.create_index('uq_reports_object_key_live', 'reports', ['object_key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_reports_object_key_live', table_name='reports', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_reports_incident', table_name='reports')
    op.create_index(op.f('uq_reports_incident_live'), 'reports', ['incident_id'], unique=True, postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###
