"""initial platform schema

Creates users, conversations, messages, corrections and the report catalog.

Two things autogenerate does not do for you, added by hand:
  * `CREATE EXTENSION vector` — the messages.embedding column needs the type to
    exist before the table referencing it is created.
  * the `pgvector` import — autogenerate emits `pgvector.sqlalchemy.vector.VECTOR`
    without importing the module, so the generated file raises NameError on a
    fresh database.

Revision ID: 225d067584d5
Revises:
Create Date: 2026-08-04 22:34:37.697800

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '225d067584d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Must precede any table using the vector type. Idempotent, and also run by
    # env.py so a partially-applied chain cannot leave it missing.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('last_seen_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject', name='uq_users_provider_subject')
    )
    op.create_index('idx_users_subject', 'users', ['subject'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conv_user_updated', 'conversations', ['user_id', 'pinned', 'updated_at'], unique=False)
    op.create_table('corrections',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('correction', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(question, ''))", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_corr_created', 'corrections', ['created_at'], unique=False)
    op.create_index('idx_corr_search', 'corrections', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('report_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('version_id', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.Column('deleted_at', sa.Float(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(title,'') || ' ' || coalesce(incident_id,''))", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_search', 'reports', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_reports_updated', 'reports', ['updated_at'], unique=False)
    op.create_index('uq_reports_incident_live', 'reports', ['incident_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('has_image', sa.Boolean(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feedback', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(text, ''))", persisted=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.CheckConstraint("role IN ('user','assistant','error')", name='ck_messages_role'),
    sa.CheckConstraint('feedback IS NULL OR feedback IN (-1, 1)', name='ck_messages_feedback'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_msg_conv', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('idx_msg_feedback', 'messages', ['feedback'], unique=False, postgresql_where=sa.text('feedback IS NOT NULL'))
    op.create_index('idx_msg_search', 'messages', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_msg_search', table_name='messages', postgresql_using='gin')
    op.drop_index('idx_msg_feedback', table_name='messages', postgresql_where=sa.text('feedback IS NOT NULL'))
    op.drop_index('idx_msg_conv', table_name='messages')
    op.drop_table('messages')
    op.drop_index('uq_reports_incident_live', table_name='reports', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_reports_updated', table_name='reports')
    op.drop_index('idx_reports_search', table_name='reports', postgresql_using='gin')
    op.drop_table('reports')
    op.drop_index('idx_corr_search', table_name='corrections', postgresql_using='gin')
    op.drop_index('idx_corr_created', table_name='corrections')
    op.drop_table('corrections')
    op.drop_index('idx_conv_user_updated', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_users_subject', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
