"""user profile avatar

Adds users.avatar_url (a small image data URI).

Autogenerate emitted a plain NOT NULL column, which fails on any table that
already has rows -- Postgres has nothing to put in the new column for them.
A server_default backfills existing rows in the same statement; it is then
dropped, so the application default in the model stays the single source of
truth for new rows.

Revision ID: ccc4c71a143c
Revises: 06a1177882ba
Create Date: 2026-08-05 14:01:19.636766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc4c71a143c'
down_revision: Union[str, Sequence[str], None] = '06a1177882ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'users',
        sa.Column('avatar_url', sa.Text(), nullable=False, server_default=''),
    )
    # The default existed only to backfill; new rows get theirs from the model.
    op.alter_column('users', 'avatar_url', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
